# Generated by Django 2.2.7 on 2019-11-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockTickers',
            new_name='StockTicker',
        ),
    ]
